const translations = {
    en: {
        nav_home: "Home",
        nav_filters: "Bio-Sand Filters",
        nav_tools: "Agricultural Tools",
        nav_benches: "Cement Benches",
        nav_contact: "Contact Us",
        nav_blog: "Blog",
        nav_letter: "Ad creator",
        hero_title: "Dipak Suppliers",
        hero_desc: "We provide high-quality bio-sand filters and agricultural tools for your community. Certified solutions for health and productivity.",
        stat_happy_clients: "Happy Clients",
        stat_experience: "Years Experience",
        stat_quality: "Quality Guarantee",
        hero_cta_products: "View Our Products",
        hero_cta_contact: "Contact Us",
        hot_products_title: "Hot Products",
        hot_products_desc: "Popular products customers ask for first.",
        hero_feature_water: "Natural water purification",
        hero_feature_tools: "Durable agricultural tools",
        hero_feature_service: "Trusted local service",
        hot_label_plow: "Bed Maker",
        hot_label_dhwani: "Dhwani Yantra",
        hot_label_bench: "Cement Bench",
        hot_label_filter: "Bio-Sand Filter",
        home_contact_whatsapp_value: "Chat instantly",
        home_contact_hours_value: "Sun - Fri, 9:00 AM - 6:00 PM",
        mobile_cta_call: "Call Now",
        mobile_cta_whatsapp: "WhatsApp",
        home_contact_strip_title: "Talk to us directly",
        home_contact_phone_label: "Call",
        home_contact_whatsapp_label: "WhatsApp",
        home_contact_location_label: "Location",
        home_contact_hours_label: "Hours",
        home_cta_title: "Need product details or pricing?",
        home_cta_desc: "Call or WhatsApp us directly for the latest product details, pricing, and availability.",
        home_cta_call: "Call Us",
        home_cta_whatsapp: "Chat on WhatsApp",
        about_title: "Who We Are?",
        about_text: "At Dipak Suppliers, we are committed to community, quality, and sustainability. As a local business, we understand the specific needs of our farmers and families. We provide durable tools and effective water purification solutions to improve health and productivity in our region.",
        products_snapshot_title: "Our Solutions",
        product_filter_title: "Bio-Sand Filter",
        product_filter_desc: "Natural household water filtration designed to provide safer and cleaner drinking water.",
        product_tools_title: "Agricultural Tools",
        product_tools_desc: "Durable, practical tools designed for local farming work and daily field use.",
        product_bench_title: "Cement Bench",
        product_bench_desc: "Strong concrete benches prepared for gardens, homes, parks, and public spaces.",
        product_view_details: "View Details",
        specs_title: "Product Specifications",
        specs_intro: "Browse our main products quickly.",
        spec_filter_title: "Bio-Sand Filter",
        spec_bench_title: "Cement Bench",
        spec_plow_title: "Bed Maker",
        spec_wheelbarrow_title: "Urbana Wheelbarrow",
        spec_dhwani_title: "Dhwani Yantra",
        spec_view_details: "View Details",
        spec_view: "View",
        spec_download: "Download",
        spec_coming_soon: "Coming Soon",
        filter_page_title: "Pure Water",
        filter_page_subtitle: "Bio-Sand Filter: Natural and Effective.",
        filter_what_title: "What is a Bio-Sand Filter?",
        filter_what_desc1: "The bio-sand filter is a variation of the traditional slow sand filter, which has been used for community water treatment for over 200 years. It is small and designed for household use.",
        filter_what_desc2: "This filter works through a natural process. Water is poured into the top and passes through layers of sand and gravel. A biological layer called 'schmutzdecke' develops on top of the sand which destroys parasites, while the sand removes particles and turbidity.",
        filter_origin_title: "Organization Behind This Technology",
        filter_origin_desc: "The household biosand filter was developed from slow sand filtration by Dr. David Manz. CAWST (Centre for Affordable Water and Sanitation Technology) is the organization most closely associated with sharing this technology globally through training, technical resources, and implementation support.",
        filter_cawst_desc: "CAWST is a Canadian charity and licensed engineering firm that helps communities improve safe drinking water, sanitation, and hygiene through practical education.",
        filter_cawst_website_label: "Website:",
        filter_gallery_title: "Gallery",
        benefits_title: "Key Benefits",
        mechanism_title: "How it Removes Bacteria?",
        mec_1_title: "Trapping",
        mec_1_desc: "Debris and pathogens get trapped in the sand as water flows through.",
        mec_2_title: "Predation",
        mec_2_desc: "Microorganisms in the biolayer eat smaller pathogens.",
        mec_3_title: "Adsorption",
        mec_3_desc: " viruses get stuck to sand grains due to electrical charge.",
        mec_4_title: "Natural Death",
        mec_4_desc: "Pathogens die due to lack of food and oxygen deep in the sand.",
        use_title: "Method of Use",
        use_step_1: "Place a clean vessel under the filter tap.",
        use_step_2: "Open the lid and pour water slowly from the top.",
        use_step_3: "Water filters through and collects in the vessel below.",
        use_step_4: "Keep the area and vessels clean to avoid contamination.",
        use_step_5: "Concrete: 25-30L/hr, Plastic: 15-20L/hr. Sufficient for a large family.",
        filter_cta_title: "Ready for Clean Water?",
        filter_cta_desc: "Ordering is easy. We provide local delivery and installation support. Contact us today or learn more.",
        cta_get_price: "Get Price",

        // Benefits
        benefit_1_title: "Low Cost",
        benefit_1_desc: "Affordable one-time investment for long-term solution. No expensive replacement parts needed.",
        benefit_2_title: "No Chemicals",
        benefit_2_desc: "Uses completely natural process to clean water. No chlorine or chemical taste.",
        benefit_3_title: "Easy Maintenance",
        benefit_3_desc: "Easy to operate and clean. Just pour water and collect clean water.",
        benefit_4_title: "Proven Results",
        benefit_4_desc: "Effectively reduces parasites, bacteria and turbidity, providing safe drinking water.",

        // Reviews
        review_kicker: "Google Reviews",
        review_title: "Trusted by Local Customers",
        review_subtitle: "Feedback from customers who use our filters, tools, and cement products.",
        review_summary_text: "Based on customer feedback from Google and direct inquiries.",
        review_summary_source: "Google feedback",
        review_1_text: "Bio-sand filter changed our life. Clean water at home!",
        review_2_text: "Excellent agricultural tools. Very durable and modern.",
        review_3_text: "The bed maker saves time and labor, with a comfortable grip and useful design.",
        review_4_text: "Excellent service and fast delivery. Will buy again!",
        review_time_1: "a month ago",
        review_time_2: "2 months ago",
        review_time_3: "3 weeks ago",
        review_time_4: "1 week ago",
        review_tag_filter: "Bio-Sand Filter",
        review_tag_tools: "Agricultural Tools",
        review_tag_bedmaker: "Bed Maker",
        review_tag_service: "Service",
        review_cta_title: "Need help choosing the right product?",
        review_cta_desc: "Call or WhatsApp us for product details, price, and availability.",
        local_guide: "Local Guide",
        reviews_count: " reviews",
        posted_on: "Posted on Google",

        // Manual
        user_manual_title: "User Manual",
        download_manual_btn: "View User Manual (Nepali)",
        manual_desc: "Download our detailed guide on how to use and maintain your Bio-Sand Filter.",
        download_spec_btn: "View Product Specification",

        tools_page_title: "Solutions for Farmers",
        tools_page_subtitle: "Safe Crop, Satisfied Farmer",
        tools_main_title: "Modern Agricultural Tools",
        tools_plow_title: "Bed Maker",
        tools_card_plow_title: "Bed Maker",
        tools_card_plow_desc: "A modern agricultural tool useful for preparing land for cultivation.",
        tools_card_wheelbarrow_title: "Strong Urbana Wheelbarrow",
        tools_card_wheelbarrow_desc: "Useful for transporting construction materials, sand, soil, and garden tools.",
        tools_card_fork_title: "Container Hoe Fork",
        tools_card_fork_desc: "A strong multi-prong farming tool used to loosen soil, control weeds, and prepare seed beds.",
        tools_card_dhwani_title: "Dhwani Yantra",
        tools_card_dhwani_desc: "Produces loud sound to scare away monkeys, elephants, and other wild animals.",
        tools_card_urea_title: "Urea Applicator",
        tools_card_urea_desc: "A field tool designed for urea application that helps improve irrigation efficiency and crop output.",
        tools_card_chulo_title: "Chulo",
        tools_card_chulo_desc: "This steel stove is a strong and durable cooking appliance made of high-quality heavy metal. Weighing around 11 kg, this stove can be used for a long time due to its sturdy structure and is suitable for daily use.",
        tools_benefits_title: "Benefits:",
        tools_benefit_1: "Saves time and labor for farmers.",
        tools_benefit_2: "Allows one person to complete more work efficiently.",
        tools_benefit_3: "The hard steel tip makes bed formation easier.",
        tools_benefit_4: "The 14-inch wheels make pulling easier.",
        tools_benefit_5_title: "Easy and durable:",
        tools_benefit_5_desc: "Simple to use and built to last.",
        tools_benefit_6_title: "Useful for bed making:",
        tools_benefit_6_desc: "Makes cultivation easier and helps improve quality production.",
        tools_benefit_7_title: "Affordable and easy to operate:",
        tools_benefit_7_desc: "A farmer-friendly tool available at lower cost.",
        tools_structure_title: "Structure:",
        tools_structure_1_title: "1. Metal frame and handle:",
        tools_structure_1_desc: "The main structure is made from strong iron or steel. It is durable, stable under heavy pressure, and designed to provide a good grip for the user.",
        tools_structure_2_title: "2. Metal blade:",
        tools_structure_2_desc: "A sharp and strong steel blade is used for cutting soil. It helps create beds easily and dig to the required depth while maintaining durability.",
        tools_structure_3_title: "3. Plastic rubber wheels:",
        tools_structure_3_desc: "Durable rubberized plastic wheels make the tool easy to operate and provide good traction on different soil types.",
        cta_inquiry: "Inquiry About Orders",
        bench_page_title: "Cement Benches",
        bench_page_subtitle: "Prepared for maximum durability using high-quality concrete.",
        bench_intro_title: "Strong and Durable",
        bench_intro_desc: "Our cement benches are built with high-quality concrete for maximum durability. Designed to withstand changing weather, they are a strong, low-maintenance option for outdoor areas, gardens, and parks.",
        bench_benefits_title: "Key Benefits",
        bench_benefit_1_title: "Weather Resistant",
        bench_benefit_1_desc: "Protected from sun, rain, and decay. These benches are suitable for outdoor use throughout the year.",
        bench_benefit_2_title: "Highly Durable",
        bench_benefit_2_desc: "Made from strong concrete, the bench stays stable and is not easy to move or steal.",
        bench_benefit_3_title: "Eco-Friendly Design",
        bench_benefit_3_desc: "A sustainable product designed with long-term use in mind and less harm to the environment.",
        bench_benefit_4_title: "Custom Design Options",
        bench_benefit_4_desc: "Available in different colors and finishes to match your space.",
        bench_features_title: "Cement Bench Highlights",
        bench_feature_1_title: "Emotionally Meaningful",
        bench_feature_1_desc: "A respectful way to preserve and honor the memory of loved ones.",
        bench_feature_2_title: "Suitable for Public Spaces",
        bench_feature_2_desc: "Easy to place in parks, bus parks, school grounds, temple surroundings, and similar areas.",
        bench_feature_3_title: "Keeps Memories Alive",
        bench_feature_3_desc: "Can be dedicated in the name of parents, grandparents, friends, or a life partner.",
        bench_feature_4_title: "Service-Oriented and Positive",
        bench_feature_4_desc: "Provides seating for the community while creating a meaningful social contribution.",
        bench_gallery_title: "Gallery",
        bench_cta_title: "Strong and Durable for Garden",
        bench_cta_desc: "Prepared for maximum durability for the garden.",
        cta_get_quote: "Get a Quote",
        contact_page_title: "Stay in Touch",
        contact_page_subtitle: "We love to hear your suggestions.",
        contact_about_title: "About Us",
        contact_about_established_title: "Established:",
        contact_about_established_desc: "Ashoj 1, 2075 BS (under Domestic Industry registration)",
        contact_info_title: "Contact Information",
        contact_feedback_title: "Give us feedback",
        contact_visit_us: "Visit Us",
        contact_call_us: "Call Us",
        contact_email_us: "Email Us",
        contact_follow_us: "Follow Us",
        contact_name_label: "Your Name",
        contact_email_label: "Email Address",
        contact_subject_label: "Subject",
        contact_message_label: "Enter your message",
        contact_name_placeholder: "Ram Bahadur",
        contact_email_placeholder: "rambahadur@gmail.com",
        contact_subject_placeholder: "Inquiry about bio-sand filter",
        contact_message_placeholder: "Enter your message here...",
        contact_send_message: "Send Message",
        contact_about_journey_title: "Our Journey:",
        contact_about_journey_desc: "Since Magh 4, 2080 BS, services expanded through 'D & D Grill Engineering'.",
        contact_about_expertise_title: "Expertise:",
        contact_about_expertise_desc: "Production of cement products and modern agricultural tools.",
        contact_about_products_title: "Main Products:",
        contact_about_products_desc: "Modern agricultural tools, cement benches, and water purification filters.",
        contact_about_quality_title: "Registration and Quality:",
        contact_about_quality_desc: "Officially registered in Morang, Koshi Province, delivering quality service.",
        blog_page_title: "Partnerships bringing safer water to communities",
        blog_page_subtitle: "Highlights from Bio-Sand Filter collaboration, school programs, and larger water-treatment installations.",
        blog_topic_water: "Clean water",
        blog_topic_partnerships: "Partnerships",
        blog_topic_schools: "School programs",
        blog_featured_kicker: "Featured partnership",
        blog_featured_heading: "Sharing knowledge for safer water",
        blog_featured_intro: "Connecting local experience with organizations working to expand safe-water solutions.",
        blog_featured_label: "Working together",
        blog_category_water: "Water & health",
        blog_category_partnership: "Partnership",
        blog_category_school: "School program",
        blog_category_collaboration: "Community collaboration",
        blog_category_installation: "School installation",
        blog_category_large_system: "Larger-capacity system",
        blog_read_4: "4 min read",
        blog_read_3: "3 min read",
        blog_card_1_title: "Bio-Sand Filter representatives connect in Nepal",
        blog_card_1_desc: "Representatives connected with Dipak Suppliers to exchange practical knowledge about Bio-Sand Filter production, use, and community impact in Nepal.",
        blog_tip_1: "Nepal Bio-Sand Filter representatives",
        blog_tip_2: "ENPHO and CAWST participation",
        blog_tip_3: "Local production and field experience",
        blog_read_guide: "Explore Bio-Sand Filters",
        blog_latest_kicker: "Community impact",
        blog_latest_heading: "Clean water in local schools",
        blog_latest_intro: "Two examples of school-focused filtration, from student awareness to a larger-capacity system.",
        blog_card_2_title: "Bio-Sand Filter program with Jadaha Rural Municipality",
        blog_card_2_desc: "Students gather around the filter during a collaborative school program involving Jadaha Rural Municipality, the school, and Dipak Suppliers.",
        blog_card_3_title: "Overhead tank filtration for school use",
        blog_card_3_desc: "This larger tank-based filtration setup is designed to support the higher daily water needs of a school community.",
        blog_explore_topic: "Learn about the filter",
        blog_press_badge: "In the news",
        blog_press_date: "Published Chaitra 20, 2081 BS",
        blog_press_kicker: "Press feature",
        blog_press_heading: "Dipak Suppliers in the news",
        blog_press_intro: "Independent coverage of our journey, local manufacturing, and vision for agriculture.",
        blog_press_desc: "The article profiles Dipak Bhandari's journey as a farmer and entrepreneur, highlighting locally made agricultural tools, Bio-Sand Filters, and his belief in creating opportunity through agriculture in Nepal.",
        blog_press_topic_1: "Agricultural innovation",
        blog_press_topic_2: "Local manufacturing",
        blog_press_topic_3: "Clean-water solutions",
        blog_press_read: "Read the full article",
        blog_video_kicker: "Featured video",
        blog_video_heading: "See our products in action",
        blog_video_intro: "Short videos offering a closer look at our products, their design, and practical uses.",
        blog_video_title: "Learn more about our cement benches",
        blog_video_desc: "Watch this Facebook reel for a closer look at the strength, practical use, and design of cement benches from Dipak Suppliers.",
        blog_video_point_1: "Built for outdoor use",
        blog_video_point_2: "Suitable for public spaces",
        blog_watch_facebook: "Watch on Facebook",
        blog_view_benches: "View cement bench details",
        blog_donor_kicker: "Helping hands",
        blog_donor_title: "Every donated bench creates a place for the community",
        blog_donor_desc: "We are grateful to the individuals, families, and organizations who donate cement benches for schools, temples, parks, and public spaces. Their continued support helps communities and helps Dipak Suppliers grow.",
        blog_donor_impact_1: "Useful seating for everyone",
        blog_donor_impact_2: "A lasting act of care",
        blog_donor_impact_3: "Support for local growth",
        blog_donor_cta: "Donate a bench",
        blog_donor_social_kicker: "Stories of support",
        blog_donor_social_title: "Meet the people behind donated benches",
        blog_donor_social_status: "Donor post coming soon",
        blog_donor_social_link: "View donor post on Facebook",
        blog_donor_video_kicker: "Another story of support",
        blog_donor_video_title: "Memorial seating added along Fulbari Marg",
        blog_donor_video_desc: "Community-minded donors supported an additional falaincha along Fulbari Marg in memory of their family members.",
        blog_donor_video_link: "Watch donor video on Facebook",
        blog_memorial_kicker: "Community memorial",
        blog_memorial_title: "Gen-Z Park: remembering lives through a shared public space",
        blog_memorial_desc: "Gen-Z Park was developed in collaboration with the youth of Ratuwamai, Morang, in memory of the young people who lost their lives during Nepal's Gen-Z movement.",
        blog_memorial_quote: "A place to remember, reflect, and carry their hopes forward together.",
        blog_memorial_location_label: "Location",
        blog_memorial_location: "Ratuwamai, Morang",
        blog_memorial_partner_label: "Collaboration",
        blog_memorial_partner: "Youth of Ratuwamai",
        blog_memorial_watch: "Watch the memorial video",
        blog_landmark_kicker: "Local place-making",
        blog_landmark_title: "A new identity pillar for Viral Fulbari",
        blog_landmark_desc: "Dipak Suppliers created an identity pillar to make Viral Fulbari at Dandatol, Urlabari-9, more attractive and recognizable.",
        blog_landmark_location_label: "Community location",
        blog_landmark_location: "Dandatol, Urlabari-9, Morang",
        blog_landmark_facebook: "View the post on Facebook",
        blog_contact_kicker: "Have a product question?",
        blog_contact_title: "Get practical advice directly from our team",
        blog_contact_desc: "Ask about product use, maintenance, current pricing, or availability.",
        footer_about: "Empowering our community with clean water and reliable tools. Dedicated to quality and sustainability in every product.",
        footer_links_title: "Quick Links",
        footer_contact_title: "Contact Us",
        footer_hours_title: "Business Hours",
        footer_update_note: "For the latest product details and pricing, contact us directly."
    },
    ne: {
        nav_home: "होम",
        nav_filters: "बायो-स्यान्ड फिल्टर",
        nav_tools: "कृषि उपकरणहरू",
        nav_benches: "सिमेन्ट बेन्च",
        nav_contact: "सम्पर्क",
        nav_blog: "ब्लग",
        nav_letter: "पत्र बनाउनुहोस्",
        hero_title: "दीपक सप्लायर्स",
        hero_desc: "हामी तपाईंको समुदायलाई उच्च गुणस्तरको बायो-स्यान्ड फिल्टर र कृषि उपकरणहरू प्रदान गर्दछौं। स्वास्थ्य र उत्पादकताको लागि प्रमाणित समाधान।",
        stat_happy_clients: "खुसी ग्राहकहरू",
        stat_experience: "वर्षको अनुभव",
        stat_quality: "गुणस्तर ग्यारेन्टी",
        hero_cta_products: "हाम्रो उत्पादनहरू हेर्नुहोस्",
        hero_cta_contact: "सम्पर्क गर्नुहोस्",
        hot_products_title: "हट प्रोडक्ट्स",
        hot_products_desc: "ग्राहकहरूले सबैभन्दा धेरै सोध्ने लोकप्रिय उत्पादनहरू।",
        hero_feature_water: "प्राकृतिक पानी शुद्धीकरण",
        hero_feature_tools: "टिकाउ कृषि उपकरण",
        hero_feature_service: "स्थानीय विश्वसनीय सेवा",
        hot_label_plow: "बेड मेकर",
        hot_label_dhwani: "ध्वनी यान्त्र",
        hot_label_bench: "सिमेन्ट बेन्च",
        hot_label_filter: "बायो-स्यान्ड फिल्टर",
        home_contact_whatsapp_value: "तुरुन्तै कुरा गर्नुहोस्",
        home_contact_hours_value: "आइत - शुक्र, बिहान ९:०० - साँझ ६:००",
        mobile_cta_call: "अहिले फोन गर्नुहोस्",
        mobile_cta_whatsapp: "व्हाट्सएप",
        home_contact_strip_title: "सिधै हामीसँग कुरा गर्नुहोस्",
        home_contact_phone_label: "फोन",
        home_contact_whatsapp_label: "व्हाट्सएप",
        home_contact_location_label: "ठेगाना",
        home_contact_hours_label: "समय",
        home_cta_title: "उत्पादन विवरण वा मूल्य चाहिन्छ?",
        home_cta_desc: "नवीनतम उत्पादन विवरण, मूल्य र उपलब्धताका लागि सिधै फोन वा व्हाट्सएप गर्नुहोस्।",
        home_cta_call: "फोन गर्नुहोस्",
        home_cta_whatsapp: "व्हाट्सएप गर्नुहोस्",
        about_title: "हामी को हौं ?",
        about_text: "दीपक सप्लायर्समा, हामी समुदाय, गुणस्तर र दिगोपनप्रति प्रतिबद्ध छौं। स्थानीय व्यवसायको रूपमा, हामी हाम्रा किसान र परिवारहरूको विशिष्ट आवश्यकताहरू बुझ्छौं। हामी हाम्रो क्षेत्रमा स्वास्थ्य र उत्पादकता सुधार गर्न टिकाउ उपकरणहरू र प्रभावकारी पानी शुद्धीकरण समाधानहरू प्रदान गर्दछौं।",
        products_snapshot_title: "हाम्रो समाधान",
        product_filter_title: "बायो-स्यान्ड फिल्टर",
        product_filter_desc: "घरायसी प्रयोगका लागि सुरक्षित र सफा पिउने पानी उपलब्ध गराउने प्राकृतिक फिल्ट्रेशन प्रणाली।",
        product_tools_title: "कृषि उपकरणहरू",
        product_tools_desc: "स्थानीय खेतीपाती र दैनिक खेत कार्यका लागि बनाइएका टिकाउ र व्यावहारिक औजारहरू।",
        product_bench_title: "सिमेन्ट बेन्च",
        product_bench_desc: "बगैंचा, घर, पार्क र सार्वजनिक स्थानका लागि तयार पारिएका बलिया कङ्क्रिट बेन्चहरू।",
        product_view_details: "विस्तृत हेर्नुहोस्",
        specs_title: "उत्पादन स्पेसिफिकेशन",
        specs_intro: "हाम्रा प्रमुख उत्पादनहरू छिटो हेर्नुहोस्। विस्तृत PDF विवरण पछि थपिनेछ।",
        spec_filter_title: "बायो-स्यान्ड फिल्टर",
        spec_bench_title: "सिमेन्ट बेन्च",
        spec_plow_title: "बेड मेकर",
        spec_wheelbarrow_title: "बलियो अर्बना ह्विलबारो",
        spec_dhwani_title: "ध्वनी यान्त्र",
        spec_view_details: "विस्तृत विवरण",
        spec_view: "हेर्नुहोस्",
        spec_download: "डाउनलोड",
        spec_coming_soon: "छिट्टै आउँदैछ",
        filter_page_title: "शुद्ध पानी",
        filter_page_subtitle: "बायो-स्यान्ड फिल्टर: प्राकृतिक र प्रभावकारी।",
        filter_what_title: "बायो-स्यान्ड फिल्टर के हो?",
        filter_what_desc1: "बायो-स्यान्ड फिल्टर परम्परागत ढिलो बालुवा फिल्टरको एक रूप हो, जुन २०० वर्षभन्दा बढी समयदेखि सामुदायिक पानी उपचारका लागि प्रयोग हुँदै आएको छ। यो सानो छ र घरघरायसी प्रयोगका लागि उपयुक्त हुने गरी बनाइएको छ।",
        filter_what_desc2: "यो फिल्टर प्राकृतिक प्रक्रिया मार्फत काम गर्दछ। पानी माथिबाट हालिन्छ र बालुवा र गिट्टीको तहहरू पार गर्दछ। बालुवाको माथि 'स्मुजडेक' (schmutzdecke) भनिने जैविक तह विकास हुन्छ जसले परजीवीहरूलाई नष्ट गर्दछ, जबकि बालुवाले कणहरू र धमिलोपन हटाउँछ।",
        filter_origin_title: "यस प्रविधिपछाडिको संस्था",
        filter_origin_desc: "घरायसी बायो-स्यान्ड फिल्टर ढिलो बालुवा फिल्ट्रेशन प्रविधिबाट डा. डेभिड म्यान्जले विकास गर्नुभएको हो। CAWST (Centre for Affordable Water and Sanitation Technology) यस प्रविधिलाई तालिम, प्राविधिक स्रोतसामग्री, र कार्यान्वयन सहयोगमार्फत विश्वभर फैलाउन नजिकबाट जोडिएको संस्था हो।",
        filter_cawst_desc: "CAWST क्यानाडाको एक परोपकारी संस्था तथा इजाजतप्राप्त इन्जिनियरिङ संस्था हो, जसले व्यवहारिक शिक्षामार्फत समुदायलाई सुरक्षित पिउने पानी, सरसफाइ, र स्वच्छतामा सहयोग गर्दछ।",
        filter_cawst_website_label: "वेबसाइट:",
        filter_gallery_title: "ग्यालरी",
        benefits_title: "मुख्य फाइदाहरू",
        mechanism_title: "बायोस्याण्ड फिल्टरले कसरी जीवाणु हटाउँदछ ?",
        mec_1_title: "१. अड्कने प्रकृया",
        mec_1_desc: "वालुवाबाट पानीको प्रवाह हुँदा पानीमा भएका फोहोरहरु र जिवाणुहरु बालुवाको माथिल्लो सतहको कणमा नै अड्कन्छ ।",
        mec_2_title: "२. जिवाणुले जिवाणुलाई खाने प्रकृया",
        mec_2_desc: "फिल्टरमा विकास हुने बायोफिल्ममा रहने ठूला जिवाणुहरुले अन्य साना जिवाणुलाई खानाको रुपमा खान्छन ।",
        mec_3_title: "३. टाँसिने प्रकृया",
        mec_3_desc: "पानीमा रहेका केही जीवाणुहरु बालुवाका कणहरुमा टाँसिदा (+र – चार्जका कारण) फिल्टर गरिएको पानीमा आउन सक्दैनन् ।",
        mec_4_title: "४. प्राकृतिक मृत्युको प्रकृया",
        mec_4_desc: "केही जीवाणुहरु पर्याप्त खाना वा अक्सिजनको कमीले वा आयु सकिएर मर्दछन् ।",
        use_title: "प्रयोग गर्ने विधि",
        use_step_1: "फिल्टर भएर आएको पानी जम्मा गर्ने भाँडो फिल्टरको टुटी तल थाप्ने ।",
        use_step_2: "फिल्टरको बिर्को खोली माथिबाट बिस्तारै पानी खन्याउने ।",
        use_step_3: "पानी फिल्टरबाट छानिएर टुटी तल थापिराखेको भाँडोमा जम्मा हुन्छ ।",
        use_step_4: "जैविक प्रदूषणबाट बच्न फिल्टर वरपर र पानी जम्मा गर्ने भाँडा सफा राख्नु पर्छ ।",
        use_step_5: "कङ्क्रिट बायोस्याण्ड फिल्टरले प्रति घण्टा २५–३० लिटर र प्लाष्टिक बायोस्याण्ड फिल्टरले प्रति घण्टा १५–२० लिटर पानी छान्छ, जुन ठूलो परिवारको लागि पनि पिउन र खाना पकाउन पर्याप्त हुन्छ ।",
        filter_cta_title: "सफा पानीको लागि तयार हुनुहुन्छ?",
        filter_cta_desc: "अर्डर गर्न सजिलो छ। हामी स्थानीय डेलिभरी र जडान सहयोग प्रदान गर्छौं। आजै हामीलाई सम्पर्क गर्नुहोस् वा थप जानकारी लिनुहोस्।",
        cta_get_price: "मूल्य बुझ्नुहोस्",

        // Benefits
        benefit_1_title: "कम लागत",
        benefit_1_desc: "दीर्घकालीन समाधानको लागि किफायती एक पटकको लगानी। कुनै महँगो प्रतिस्थापन पार्ट्स आवश्यक पर्दैन।",
        benefit_2_title: "कुनै रसायन छैन",
        benefit_2_desc: "पानी सफा गर्न पूर्ण रूपमा प्राकृतिक प्रक्रिया प्रयोग गर्दछ। क्लोरीन वा रासायनिक स्वाद हुँदैन।",
        benefit_3_title: "सजिलो मर्मतसम्भार",
        benefit_3_desc: "सञ्चालन र सफा गर्न सजिलो। मात्र पानी हाल्नुहोस् र सफा पानी जम्मा गर्नुहोस्।",
        benefit_4_title: "प्रमाणित नतिजाहरू",
        benefit_4_desc: "परजीवी, ब्याक्टेरिया र धमिलोपनलाई प्रभावकारी रूपमा घटाउँछ, सुरक्षित पिउने पानी प्रदान गर्दछ।",

        // Reviews
        review_kicker: "Google समीक्षा",
        review_title: "स्थानीय ग्राहकहरूको विश्वास",
        review_subtitle: "हाम्रा फिल्टर, औजार र सिमेन्ट उत्पादन प्रयोग गर्ने ग्राहकहरूको प्रतिक्रिया।",
        review_summary_text: "Google र प्रत्यक्ष सोधपुछबाट प्राप्त ग्राहक प्रतिक्रियामा आधारित।",
        review_summary_source: "Google प्रतिक्रिया",
        review_1_text: "बायो-स्यान्ड फिल्टरले हाम्रो जीवन परिवर्तन गर्‍यो। घरमा सफा पानी!",
        review_2_text: "उत्कृष्ट कृषि औजारहरू। धेरै टिकाउ र आधुनिक ।",
        review_3_text: "समय र श्रमको बचत गर्ने, प्रयोगकर्तालाई राम्रो पकड दिने सुविधायुक्त डिजाइन भएको बेड मेकर।",
        review_4_text: "उत्कृष्ट सेवा र छिटो डेलिभरी। फेरि किन्नेछु!",
        review_time_1: "एक महिना अघि",
        review_time_2: "२ महिना अघि",
        review_time_3: "३ हप्ता अघि",
        review_time_4: "१ हप्ता अघि",
        review_tag_filter: "बायो-स्यान्ड फिल्टर",
        review_tag_tools: "कृषि उपकरणहरू",
        review_tag_bedmaker: "बेड मेकर",
        review_tag_service: "सेवा",
        review_cta_title: "सही उत्पादन छान्न सहयोग चाहिन्छ?",
        review_cta_desc: "उत्पादन विवरण, मूल्य र उपलब्धताका लागि फोन वा WhatsApp गर्नुहोस्।",
        local_guide: "स्थानीय गाइड",
        reviews_count: " समीक्षाहरू",
        posted_on: "Google मा पोस्ट गरिएको",

        // Manual
        user_manual_title: "प्रयोगकर्ता पुस्तिका",
        download_manual_btn: "नेपाली प्रयोगकर्ता पुस्तिका हेर्नुहोस्",
        manual_desc: "तपाईंको बायो-स्यान्ड फिल्टरको प्रयोग र मर्मतसम्भार कसरी गर्ने भन्ने बारे विस्तृत जानकारी डाउनलोड गर्नुहोस्।",
        download_spec_btn: "उत्पादन स्पेसिफिकेशन हेर्नुहोस्",

        tools_page_title: "किसानको लागि समाधान",
        tools_page_subtitle: "सुरक्षित बाली, सन्तुष्ट किसान",
        tools_main_title: "आधुनिक कृषि औजार",
        tools_plow_title: "बेड मेकर",
        tools_card_plow_title: "बेड मेकर",
        tools_card_plow_desc: "खेतीका लागि जमिन तयार पार्न उपयोगी आधुनिक कृषि औजार।",
        tools_card_wheelbarrow_title: "बलियो अर्बना ह्विलबारो",
        tools_card_wheelbarrow_desc: "निर्माण सामग्री (इँटा, कंक्रीट), बालुवा, र बगैंचाका सामानहरू (माटो, औजारहरू) ढुवानी गर्ने।",
        tools_card_fork_title: "काँटेदार खन्ती",
        tools_card_fork_desc: "काँटेदार खन्ती खेती गर्ने औजार हो जसमा माटोलाई हावा दिने, झारपात नियन्त्रण गर्ने र रोपणको लागि बीउको ड्याङ तयार पार्न प्रयोग गरिने बलियो दाँतहरू (प्रङहरू) हुन्छन्।",
        tools_card_dhwani_title: "ध्वनी यान्त्र",
        tools_card_dhwani_desc: "ठूलो आवाज उत्पादन गरी जनावरहरूलाई डराएर टाढा भगाउँछ। बाँदर, हात्ती र अन्य जंगली जनावरहरूबाट बच्नको लागि उत्कृष्ट समाधान।",
        tools_card_urea_title: "युरिया लगाउने",
        tools_card_urea_desc: "युरिया लगाउने औजार हो जसमा गोडमेल गरेर सिँचाइ गर्दा डब्बल उत्पादन हुन्छ।",
        tools_card_chulo_title: "चुलो",
        tools_card_chulo_desc: "यो स्टिलको चुलो उच्च गुणस्तरको भारी धातुबाट बनेको बलियो र टिकाउ खाना पकाउने उपकरण हो। करिब ११ केजी तौल भएको यो चुलोको बनावट मजबुत भएकाले लामो समयसम्म दैनिक प्रयोगका लागि उपयुक्त हुन्छ।",
        tools_benefits_title: "फाइदाहरू :",
        tools_benefit_1: "किसानहरूका लागि समय र श्रमको बचत गर्दछ।",
        tools_benefit_2: "एक जना व्यक्तिले पनि धेरै काम गर्न सक्ने क्षमता हुन्छ।",
        tools_benefit_3: "हलोको टुप्पोमा हार्ड स्टील प्रयोग गरिएको हुनाले ड्याङ बनाउन सहज हुन्छ।",
        tools_benefit_4: "हलोमा १४ इन्चका पाङ्ग्रा प्रयोग गरिएकाले तान्न सजिलो हुन्छ।",
        tools_benefit_5_title: "सहज र टिकाउ:",
        tools_benefit_5_desc: "प्रयोग गर्न सजिलो र लामो समयसम्म बिग्रँदैन।",
        tools_benefit_6_title: "बेड बनाउन प्रयोगयोग्य:",
        tools_benefit_6_desc: "खेती गरौं सजिलो तरिकाले, उत्पादन बढाऔं गुणस्तरीय!",
        tools_benefit_7_title: "सस्तो र चलाउन सजिलो:",
        tools_benefit_7_desc: "कम खर्चमा किन्न सकिने र किसानमैत्री उपकरण।",
        tools_structure_title: "बनावट :",
        tools_structure_1_title: "१. धातु फ्रेम र ह्याण्डल :",
        tools_structure_1_desc: "उपकरणको मुख्य संरचना बलियो फलाम (स्टिल) बाट निर्माण गरिएको छ। यो लामो समयसम्म टिकाउ, मजबुत र अत्यधिक दबाबमा पनि नबंगिने किसिमको हुन्छ। प्रयोगकर्तालाई राम्रो पकड दिन सक्ने सुविधायुक्त डिजाइन गरिएको छ।",
        tools_structure_2_title: "२. धातु ब्लेड :",
        tools_structure_2_desc: "माटो काट्न मिल्ने तेज र बलियो स्टीलको ब्लेड प्रयोग गरिएको छ। ब्लेडले सजिलै बेड निर्माण गर्न र आवश्यक गहिराइसम्म माटो खन्न सहयोग गर्दछ। लामो समयसम्म धार कायम रहने गुणस्तरीय स्टील प्रयोग गरिएको छ।",
        tools_structure_3_title: "३. प्लास्टिक रबर पाङ्ग्रा :",
        tools_structure_3_desc: "उपकरणलाई सजिलै सञ्चालन गर्न सकिने टिकाउ रबरयुक्त प्लास्टिक पाङ्ग्रा प्रयोग गरिएको छ। विभिन्न प्रकारका माटोमा राम्रो पकड (ट्र्याक्सन) प्रदान गर्ने किसिमको बनावट रहेको छ।",
        cta_inquiry: "अर्डरहरूको बारेमा सोधपुछ गर्नुहोस्",
        bench_page_title: "सिमेन्ट बेन्च",
        bench_page_subtitle: "उच्च गुणस्तरको कङ्क्रिट प्रयोग गरी अधिकतम टिकाउपनको लागि तयार पारिएका छन्।",
        bench_intro_title: "बलियो र टिकाउ",
        bench_intro_desc: "हाम्रा सिमेन्ट बेन्चहरू उच्च गुणस्तरको कङ्क्रिट प्रयोग गरी अधिकतम टिकाउपनको लागि तयार पारिएका छन्। जस्तोसुकै मौसम पनि थाम्न सक्ने गरी बनाइएका यी बेन्चहरू घरबाहिर, बगैंचा वा पार्कहरूका लागि अति उत्तम र कम मर्मत चाहिने विकल्प हुन्।",
        bench_benefits_title: "मुख्य फाइदाहरू",
        bench_benefit_1_title: "मौसम प्रतिरोधी",
        bench_benefit_1_desc: "घाम, पानी र सड्ने समस्याबाट मुक्त। यी बेन्चहरू बाह्रै महिना बाहिर राख्नका लागि उपयुक्त छन्।",
        bench_benefit_2_title: "अत्यधिक बलियो",
        bench_benefit_2_desc: "बलियो कङ्क्रिटले बनेको हुनाले यो स्थिर रहन्छ र चोरी हुने वा सर्ने डर हुँदैन।",
        bench_benefit_3_title: "वातावरणमैत्री डिजाइन",
        bench_benefit_3_desc: "प्रकृतिलाई हानी नगर्ने, दिगो सोचमा आधारित उत्पादन",
        bench_benefit_4_title: "रोजाइ अनुसारको डिजाइन",
        bench_benefit_4_desc: "तपाईंको ठाउँ सुहाउँदो विभिन्न रङ र फिनिसिङहरूमा उपलब्ध छन्।",
        bench_features_title: "सिमेन्ट बेन्चका विशेषताहरू",
        bench_feature_1_title: "भावनात्मक रूपमा विशेष",
        bench_feature_1_desc: "प्रियजनको सम्झनालाई सम्मानपूर्वक जगेर्ना गर्ने माध्यम",
        bench_feature_2_title: "सार्वजनिक स्थानका लागि उपयुक्त",
        bench_feature_2_desc: "पार्क, बसपार्क, विद्यालय परिसर, मन्दिर वरिपरि आदिमा सजिलै राख्न मिल्ने",
        bench_feature_3_title: "स्मृतिलाई जीवित राख्ने माध्यम",
        bench_feature_3_desc: "बाबा–आमा, हजुरबुबा–हजुरआमा, साथी वा जीवनसाथीको नामसहित समर्पित गर्न सकिने",
        bench_feature_4_title: "सेवामूलक र सकारात्मक पहल",
        bench_feature_4_desc: "समाजलाई बस्ने ठाउँ प्रदान गर्दै पुण्य कमाउने अवसर",
        bench_gallery_title: "ग्यालरी",
        bench_cta_title: "बगैंचाको लागि बलियो र टिकाउ",
        bench_cta_desc: "बगैंचाको लागि बलियो र टिकाउपनको लागि तयार पारिएका छन्।",
        cta_get_quote: "कोटेशन लिनुहोस्",
        contact_page_title: "सम्पर्कमा रहनुहोस्",
        contact_page_subtitle: "हामीलाई तपाईंको सुझाव सुन्न मन पर्छ।",
        contact_about_title: "हाम्रो बारेमा",
        contact_about_established_title: "स्थापना:",
        contact_about_established_desc: "२०७५ असोज १ (घरेलु उद्योग अन्तर्गत)",
        contact_info_title: "सम्पर्क जानकारी",
        contact_feedback_title: "हामीलाई प्रतिक्रिया दिनुहोस्",
        contact_visit_us: "हामीलाई भेट्नुहोस्",
        contact_call_us: "हामीलाई फोन गर्नुहोस्",
        contact_email_us: "हामीलाई इमेल गर्नुहोस्",
        contact_follow_us: "हामीलाई फलो गर्नुहोस्",
        contact_name_label: "तपाईंको नाम",
        contact_email_label: "इमेल ठेगाना",
        contact_subject_label: "विषय",
        contact_message_label: "तपाईंको सन्देश लेख्नुहोस्",
        contact_name_placeholder: "राम बहादुर",
        contact_email_placeholder: "rambahadur@gmail.com",
        contact_subject_placeholder: "बायो-स्यान्ड फिल्टर सम्बन्धी जानकारी",
        contact_message_placeholder: "यहाँ आफ्नो सन्देश लेख्नुहोस्...",
        contact_send_message: "सन्देश पठाउनुहोस्",
        contact_about_journey_title: "हाम्रो यात्रा:",
        contact_about_journey_desc: "२०८० माघ ४ गतेदेखि 'डि एण्ड डि ग्रिल इन्जिनियरिङ' मार्फत सेवा विस्तार।",
        contact_about_expertise_title: "विशेषज्ञता:",
        contact_about_expertise_desc: "सिमेन्ट सामग्री र उन्नत कृषि औजारहरूको उत्पादन।",
        contact_about_products_title: "मुख्य उत्पादनहरू:",
        contact_about_products_desc: "आधुनिक कृषि औजार, सिमेन्ट बेन्च तथा पानी शुद्धीकरण फिल्टर।",
        contact_about_quality_title: "दर्ता र गुणस्तर:",
        contact_about_quality_desc: "कोशी प्रदेश, मोरङमा विधिवत दर्ता भई स्तरीय सेवा।",
        blog_page_title: "समुदायमा सुरक्षित पानी पुर्‍याउने साझेदारी",
        blog_page_subtitle: "बायो-स्यान्ड फिल्टर सहकार्य, विद्यालय कार्यक्रम र ठूला पानी प्रशोधन जडानका झलकहरू।",
        blog_topic_water: "सफा पानी",
        blog_topic_partnerships: "साझेदारी",
        blog_topic_schools: "विद्यालय कार्यक्रम",
        blog_featured_kicker: "विशेष साझेदारी",
        blog_featured_heading: "सुरक्षित पानीका लागि ज्ञान आदानप्रदान",
        blog_featured_intro: "सुरक्षित पानीका समाधान विस्तार गर्ने संस्थाहरूसँग स्थानीय अनुभव जोड्दै।",
        blog_featured_label: "सँगै काम गर्दै",
        blog_category_water: "पानी र स्वास्थ्य",
        blog_category_partnership: "साझेदारी",
        blog_category_school: "विद्यालय कार्यक्रम",
        blog_category_collaboration: "सामुदायिक सहकार्य",
        blog_category_installation: "विद्यालय जडान",
        blog_category_large_system: "ठूलो क्षमताको प्रणाली",
        blog_read_4: "४ मिनेट पढाइ",
        blog_read_3: "३ मिनेट पढाइ",
        blog_card_1_title: "नेपालमा बायो-स्यान्ड फिल्टर प्रतिनिधिहरूको भेट",
        blog_card_1_desc: "प्रतिनिधिहरूले दिपक सप्लायर्ससँग बायो-स्यान्ड फिल्टरको उत्पादन, प्रयोग र नेपालमा यसको सामुदायिक प्रभावबारे व्यवहारिक ज्ञान आदानप्रदान गरे।",
        blog_tip_1: "नेपालका बायो-स्यान्ड फिल्टर प्रतिनिधि",
        blog_tip_2: "ENPHO र CAWST को सहभागिता",
        blog_tip_3: "स्थानीय उत्पादन र मैदानी अनुभव",
        blog_read_guide: "बायो-स्यान्ड फिल्टर हेर्नुहोस्",
        blog_latest_kicker: "सामुदायिक प्रभाव",
        blog_latest_heading: "स्थानीय विद्यालयमा सफा पानी",
        blog_latest_intro: "विद्यार्थी सचेतनादेखि ठूलो क्षमताको प्रणालीसम्म विद्यालय केन्द्रित फिल्ट्रेशनका दुई उदाहरण।",
        blog_card_2_title: "जहदा गाउँपालिकासँग बायो-स्यान्ड फिल्टर कार्यक्रम",
        blog_card_2_desc: "जहदा गाउँपालिका, विद्यालय र दिपक सप्लायर्सको सहकार्यमा आयोजित कार्यक्रममा विद्यार्थीहरू फिल्टर वरिपरि भेला भएका छन्।",
        blog_card_3_title: "विद्यालयका लागि ओभरहेड ट्याङ्की फिल्ट्रेशन",
        blog_card_3_desc: "ठूलो ट्याङ्कीमा आधारित यो फिल्ट्रेशन प्रणाली विद्यालय समुदायको बढी दैनिक पानी आवश्यकता पूरा गर्न डिजाइन गरिएको हो।",
        blog_explore_topic: "फिल्टरबारे जान्नुहोस्",
        blog_press_badge: "समाचारमा",
        blog_press_date: "चैत २०, २०८१ मा प्रकाशित",
        blog_press_kicker: "प्रेस फिचर",
        blog_press_heading: "समाचारमा दिपक सप्लायर्स",
        blog_press_intro: "हाम्रो यात्रा, स्थानीय उत्पादन र कृषिसम्बन्धी सोचबारे स्वतन्त्र समाचार सामग्री।",
        blog_press_desc: "यस लेखमा किसान तथा उद्यमी दिपक भण्डारीको यात्रा, नेपालमै निर्मित कृषि औजार, बायो-स्यान्ड फिल्टर र कृषिमार्फत अवसर सिर्जना गर्न सकिने उहाँको विश्वासलाई प्रस्तुत गरिएको छ।",
        blog_press_topic_1: "कृषि नवप्रवर्तन",
        blog_press_topic_2: "स्थानीय उत्पादन",
        blog_press_topic_3: "सफा पानीका समाधान",
        blog_press_read: "पूरा समाचार पढ्नुहोस्",
        blog_video_kicker: "विशेष भिडियो",
        blog_video_heading: "हाम्रा उत्पादन प्रयोगमा हेर्नुहोस्",
        blog_video_intro: "हाम्रा उत्पादन, डिजाइन र व्यवहारिक प्रयोगलाई नजिकबाट देखाउने छोटा भिडियोहरू।",
        blog_video_title: "हाम्रो सिमेन्ट बेन्चबारे थप जान्नुहोस्",
        blog_video_desc: "दिपक सप्लायर्सका सिमेन्ट बेन्चको बलियोपन, व्यवहारिक प्रयोग र डिजाइन नजिकबाट हेर्न यो फेसबुक रिल हेर्नुहोस्।",
        blog_video_point_1: "बाहिरी प्रयोगका लागि निर्मित",
        blog_video_point_2: "सार्वजनिक स्थानका लागि उपयुक्त",
        blog_watch_facebook: "फेसबुकमा हेर्नुहोस्",
        blog_view_benches: "सिमेन्ट बेन्चको विवरण हेर्नुहोस्",
        blog_donor_kicker: "सहयोगी हातहरू",
        blog_donor_title: "दान गरिएको प्रत्येक बेन्चले समुदायका लागि बस्ने ठाउँ बनाउँछ",
        blog_donor_desc: "विद्यालय, मन्दिर, पार्क र सार्वजनिक स्थानका लागि सिमेन्ट बेन्च दान गर्ने व्यक्ति, परिवार र संस्थाहरूप्रति हामी आभारी छौं। उहाँहरूको निरन्तर सहयोगले समुदायलाई सेवा पुर्‍याउनुका साथै दिपक सप्लायर्सलाई अगाडि बढ्न मद्दत गर्छ।",
        blog_donor_impact_1: "सबैका लागि उपयोगी बस्ने ठाउँ",
        blog_donor_impact_2: "सद्भावको दीर्घकालीन चिनो",
        blog_donor_impact_3: "स्थानीय विकासमा सहयोग",
        blog_donor_cta: "बेन्च दान गर्नुहोस्",
        blog_donor_social_kicker: "सहयोगका कथाहरू",
        blog_donor_social_title: "दान गरिएका बेन्चपछाडिका सहयोगीहरूलाई चिन्नुहोस्",
        blog_donor_social_status: "दाताको पोस्ट छिट्टै आउँदैछ",
        blog_donor_social_link: "दाताको पोस्ट फेसबुकमा हेर्नुहोस्",
        blog_donor_video_kicker: "सहयोगको अर्को कथा",
        blog_donor_video_title: "फुलबारी मार्गमा थप स्मृति फलैँचा",
        blog_donor_video_desc: "समाजसेवी दाताहरूले परिवारका सदस्यहरूको स्मृतिमा फुलबारी मार्गमा थप फलैँचा निर्माणका लागि सहयोग गर्नुभएको छ।",
        blog_donor_video_link: "दाताको भिडियो फेसबुकमा हेर्नुहोस्",
        blog_memorial_kicker: "सामुदायिक स्मारक",
        blog_memorial_title: "जेन-जी पार्क: साझा सार्वजनिक स्थानमार्फत जीवनहरूको सम्झना",
        blog_memorial_desc: "नेपालको जेन-जी आन्दोलनमा ज्यान गुमाएका युवाहरूको सम्झनामा मोरङको रतुवामाईका युवाहरूसँगको सहकार्यमा जेन-जी पार्क निर्माण गरिएको हो।",
        blog_memorial_quote: "सम्झना, मनन र उहाँहरूको आशालाई सँगै अगाडि बढाउने एउटा स्थान।",
        blog_memorial_location_label: "स्थान",
        blog_memorial_location: "रतुवामाई, मोरङ",
        blog_memorial_partner_label: "सहकार्य",
        blog_memorial_partner: "रतुवामाईका युवा",
        blog_memorial_watch: "स्मारक भिडियो हेर्नुहोस्",
        blog_landmark_kicker: "स्थानीय स्थानको पहिचान",
        blog_landmark_title: "भाइरल फुलबारीका लागि नयाँ चिनारी स्तम्भ",
        blog_landmark_desc: "उर्लाबारी-९ डाँडाटोलस्थित भाइरल फुलबारीलाई थप आकर्षक र चिनिने बनाउन दिपक सप्लायर्सले चिनारी स्तम्भ निर्माण गरेको हो।",
        blog_landmark_location_label: "सामुदायिक स्थान",
        blog_landmark_location: "डाँडाटोल, उर्लाबारी-९, मोरङ",
        blog_landmark_facebook: "फेसबुक पोस्ट हेर्नुहोस्",
        blog_contact_kicker: "उत्पादनसम्बन्धी प्रश्न छ?",
        blog_contact_title: "हाम्रो टोलीबाट सिधै व्यवहारिक सल्लाह लिनुहोस्",
        blog_contact_desc: "उत्पादनको प्रयोग, मर्मत, हालको मूल्य वा उपलब्धताबारे सोध्नुहोस्।",
        footer_about: "हाम्रो समुदायलाई सफा पानी र भरपर्दो उपकरणमार्फत सशक्त बनाउँदै। हरेक उत्पादनमा गुणस्तर र दिगोपनप्रति समर्पित।",
        footer_links_title: "द्रुत लिङ्कहरू",
        footer_contact_title: "सम्पर्क गर्नुहोस्",
        footer_hours_title: "व्यवसायिक समय",
        footer_update_note: "नवीनतम उत्पादन विवरण र मूल्यका लागि सिधै हामीलाई सम्पर्क गर्नुहोस्।"
    }
};

document.addEventListener('DOMContentLoaded', () => {
    const navbar = document.querySelector('.navbar');

    function updateNavbarScrollState() {
        if (!navbar) return;
        if (window.scrollY > 12) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }
    }

    updateNavbarScrollState();
    window.addEventListener('scroll', updateNavbarScrollState, { passive: true });

    // --- Theme Logic ---
    const themeToggle = document.getElementById('theme-toggle');
    const currentTheme = localStorage.getItem('theme') || 'light';

    if (currentTheme === 'dark') {
        document.documentElement.setAttribute('data-theme', 'dark');
    }

    if (themeToggle) {
        themeToggle.addEventListener('click', () => {
            let theme = document.documentElement.getAttribute('data-theme');
            if (theme === 'dark') {
                document.documentElement.removeAttribute('data-theme');
                localStorage.setItem('theme', 'light');
            } else {
                document.documentElement.setAttribute('data-theme', 'dark');
                localStorage.setItem('theme', 'dark');
            }
        });
    }

    // --- Language Logic ---
    const langBtn = document.getElementById('lang-toggle-btn');
    const currentLang = localStorage.getItem('lang') || 'en';

    function updateLanguage(lang) {
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang] && translations[lang][key]) {
                el.textContent = translations[lang][key];
            }
        });
        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (translations[lang] && translations[lang][key]) {
                el.setAttribute('placeholder', translations[lang][key]);
            }
        });

        // Update button text to show the OTHER language (toggle action)
        if (langBtn) {
            if (lang === 'en') {
                langBtn.textContent = 'NE';
            } else {
                langBtn.textContent = 'EN'; // EN text for button when current is NE
            }
        }

        localStorage.setItem('lang', lang);
        document.documentElement.lang = lang;
    }

    // Initialize Language
    updateLanguage(currentLang);

    if (langBtn) {
        langBtn.addEventListener('click', () => {
            const current = localStorage.getItem('lang') || 'en';
            const newLang = current === 'en' ? 'ne' : 'en';
            updateLanguage(newLang);
        });
    }

    // --- Mobile Menu Toggle ---
    const mobileBtn = document.querySelector('.mobile-menu-btn');
    const navLinks = document.querySelector('.nav-links');

    if (mobileBtn) {
        mobileBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            navLinks.classList.toggle('active');
            if (navLinks.classList.contains('active')) {
                mobileBtn.textContent = '✕';
            } else {
                mobileBtn.textContent = '☰';
            }
        });

        document.addEventListener('click', (e) => {
            if (navLinks.classList.contains('active') && !navLinks.contains(e.target) && e.target !== mobileBtn) {
                navLinks.classList.remove('active');
                mobileBtn.textContent = '☰';
            }
        });

        navLinks.querySelectorAll('a').forEach(link => {
            link.addEventListener('click', () => {
                navLinks.classList.remove('active');
                mobileBtn.textContent = '☰';
            });
        });
    }

    // --- Smooth Scroll for Anchor Links ---
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth'
                });
                if (navLinks.classList.contains('active')) {
                    navLinks.classList.remove('active');
                }
            }
        });
    });
});
